# Generated by Django 3.0.6 on 2020-05-08 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_blogcomments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
